package com.ycngmn.prothomalo.utils

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.drawable.BitmapDrawable
import coil.ImageLoader
import coil.request.ImageRequest
import coil.request.SuccessResult
import java.io.File

// Generated by ChatGPT

suspend fun downloadAndSaveImage(context: Context, imageUrl: String, subDir: String, fileName: String): File? {
    val imageLoader = ImageLoader(context)
    val request = ImageRequest.Builder(context)
        .data(imageUrl)
        .allowHardware(false) // Required for converting to bitmap
        .build()

    val result = (imageLoader.execute(request) as? SuccessResult)?.drawable
    val bitmap = (result as? BitmapDrawable)?.bitmap ?: return null

    val directory = File(context.filesDir, subDir)
    if (!directory.exists()) directory.mkdirs()

    val file = File(directory, fileName)
    file.outputStream().use { outputStream ->
        bitmap.compress(Bitmap.CompressFormat.PNG, 100, outputStream)
    }
    return file
}

fun loadSavedImage(context: Context, fileName: String): Bitmap? {
    val file = File(context.filesDir, fileName)
    return if (file.exists()) BitmapFactory.decodeFile(file.absolutePath) else null
}